module.exports = {
  purge: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  darkMode: false, // or 'media' or 'class'
  theme: {
    container: {
      center: true,
    },
    colors: {
      blue: "#219EBC",
      lightblue: "#8ECAE6",
      transparent: "transparent",
      current: "currentColor",
      black: "black",
      white: "white",
      gray: "gray",
      red: "pink",
      yellow: "#FFB703",
      darkyellow: "#FB8500",
      lightestblue: "#8ECAE6",
      purple: "#7a3dd7",
      primary: "#00DFD8",
      secondary: "#7928CA",
      danger: "#ff4d4d",
    },
    fontSize: {
      xs: ".75rem",
      sm: ".875rem",
      tiny: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
      "10xl": "10rem",
    },
    gradient: {},
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
